-- CREATE DEPARTMENT TABLE

CREATE TABLE DEPARTMENT 
(
    DEPTNO      INT             NOT NULL,
    DEPTNAME    VARCHAR(20),
    FLOOR       INT,
    PRIMARY KEY (DEPTNO)
);

-- CREATE EMPLOYEE TABLE

CREATE TABLE EMPLOYEE 
(
    EMPNO       INT             NOT NULL,
    EMPNAME     VARCHAR(20)     UNIQUE,
    TITLE       VARCHAR(20)     DEFAULT '사원',
    MANAGER     INT,
    SALARY      INT             CHECK (SALARY < 6000000),
    DNO         INT             DEFAULT '1' CHECK(DNO IN (1,2,3,4)),
    PRIMARY KEY(EMPNO),
    FOREIGN KEY(MANAGER) REFERENCES EMPLOYEE(EMPNO),
    FOREIGN KEY(DNO) REFERENCES DEPARTMENT(DEPTNO)
)

-- DEPARTMENT INSERT

INSERT INTO DEPARTMENT VALUES (1 , '영업' , 8);
INSERT INTO DEPARTMENT VALUES (2 , '기획' , 10);
INSERT INTO DEPARTMENT VALUES (3 , '개발' , 9);
INSERT INTO DEPARTMENT VALUES (4 , '총무' , 7);

-- INSERT EMPLOYEE 

INSERT INTO EMPLOYEE VALUES( 4377 , '이성래' , '사장' , NULL , 5000000 , 2);
INSERT INTO EMPLOYEE VALUES( 3426 , '박영권' , '과장' , 4377 , 3000000 , 1);
INSERT INTO EMPLOYEE VALUES( 3011 , '이수민' , '부장' , 4377 , 4000000 , 3);
INSERT INTO EMPLOYEE VALUES( 1003 , '조민희' , '과장' , 4377 , 3000000 , 2);
INSERT INTO EMPLOYEE VALUES( 2106 , '김창섭' , '대리' , 1003 , 2500000 , 3);
INSERT INTO EMPLOYEE VALUES( 3427 , '최종철' , '사원' , 3011 , 1500000 , 1);
INSERT INTO EMPLOYEE VALUES( 1365 , '김상원' , '사원' , 3426 , 1500000 , 2);


